# Generated by Django 5.0.6 on 2024-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costomers",
            name="number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
