# Generated by Django 5.0.6 on 2024-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0002_remove_employee_title_alter_employee_tc"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
