# Generated by Django 5.0.6 on 2024-07-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0006_alter_employee_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_by",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
