# Generated by Django 5.0.6 on 2024-08-02 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0013_employee_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="effective_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
