# Generated by Django 5.0.6 on 2024-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0015_employee_is_working"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayment",
            name="payment_token",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
