# Generated by Django 5.0.6 on 2024-08-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0016_employeepayment_payment_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeepayment",
            name="note",
            field=models.TextField(default="None"),
        ),
    ]
