# Generated by Django 5.0.6 on 2024-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_company_customuser_company_tr"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="adress",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
