# Generated by Django 5.0.6 on 2024-07-07 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biles", "0006_udsbill_inner_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="udsbills",
            name="net",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="udsbills",
            name="top",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
    ]
