# Generated by Django 5.0.6 on 2024-06-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clints",
            name="clint_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="clints",
            name="clint_iban",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clints",
            name="clint_tex",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
