# Generated by Django 5.0.6 on 2024-06-23 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_clints_clint_email_alter_clints_clint_iban_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyes",
            name="name",
        ),
    ]
