# Generated by Django 5.0.6 on 2024-07-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_alter_costomers_is_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costomers",
            name="tex",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
