# Generated by Django 5.0.6 on 2024-08-01 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoneySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Account"),
                            ("bank", "Bank Account"),
                            ("company_bank", "Company Bank Account"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("note", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.moneysource",
                    ),
                ),
            ],
        ),
    ]
