# Generated by Django 5.0.6 on 2024-07-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biles", "0005_udsbill_inner"),
    ]

    operations = [
        migrations.AddField(
            model_name="udsbill_inner",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
