# Generated by Django 5.0.6 on 2024-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0005_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_by",
            field=models.IntegerField(),
        ),
    ]
