# Generated by Django 5.0.6 on 2024-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0007_alter_employee_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="ispyed",
            field=models.BooleanField(default=False),
        ),
    ]
