# Generated by Django 5.0.6 on 2024-08-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0010_employeepayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="effective_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
