# Generated by Django 5.0.6 on 2024-08-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0011_alter_salary_effective_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="E_salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
