# Generated by Django 5.0.6 on 2024-08-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employe", "0014_alter_salary_effective_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_working",
            field=models.BooleanField(default=True),
        ),
    ]
