# Generated by Django 5.0.6 on 2024-08-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpayment",
            name="source",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="money.moneysource",
            ),
        ),
    ]
