# Generated by Django 5.0.6 on 2024-08-03 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("money", "0002_alter_generalpayment_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpayment",
            name="payment_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
